#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
NAME=ldn
DAEMON=/usr/libexec/ldn/ldn-daemon

start_service() {
    procd_open_instance
    procd_set_param command "$DAEMON"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall ldn-daemon
}

reload_service() {
    ubus call ldn reload_config
}